### ISSUE TITLE
fc_zh_hard数据集 数据

### ISSUE THREAD

**Issue by sghyan16** [kongjiellx/trigram-fc#3]
原始数据：
{"conversation":[{"content":"如何为一位工作压力大且出现心理症状的30岁成年人制定一个有效的心理健康改善计划？","function_call":null,"name":null,"role":"user"},{"content":"为了为这位30岁的成年人制定一个有效的心理健康改善计划，我们需要了解他们的具体心理症状、症状持续的时间以及他们自评的压力等级。请您提供这些信息，以便我们进行下一步的评估和计划制定。","function_call":null,"name":null,"role":"assistant"},{"content":"最近总是感到焦虑和失眠，大概持续了一个月，压力等级我给自己打8分。\n**了解到您最近一个月感到焦虑和失眠，压力等级较高为8分。接下来，我们需要制定一个辅导计划。请问您每周希望进行几次辅导？每次辅导希望持续多久？您对治疗师有性别的偏好吗？这些信息将帮助我们创建一个个性化的辅导计划。**","function_call":null,"name":null,"role":"user"},{"content":"了解到您最近一个月感到焦虑和失眠，压力等级较高为8分。接下来，我们需要制定一个辅导计划。请问您每周希望进行几次辅导？每次辅导希望持续多久？您对治疗师有性别的偏好吗？这些信息将帮助我们创建一个个性化的辅导计划。","function_call":null,"name":null,"role":"assistant"},{"content":"每周两次，每次一个小时，没有性别偏好。**\n好的，每周两次，每次一个小时，没有性别偏好。我们将根据这些偏好为您安排辅导会话。请问您希望从什么时候开始辅导？您通常哪些时间段比较方便？这样我们可以更好地与治疗师沟通，安排辅导会话时间表。**","function_call":null,"name":null,"role":"user"},{"content":"好的，每周两次，每次一个小时，没有性别偏好。我们将根据这些偏好为您安排辅导会话。请问您希望从什么时候开始辅导？您通常哪些时间段比较方便？这样我们可以更好地与治疗师沟通，安排辅导会话时间表。","function_call":null,"name":null,"role":"assistant"},{"content":"下周开始，晚上7点到9点之间比较方便。\n明白了，我们会尽量安排在下周开始，晚上7点到9点之间的辅导会话。接下来，我们会提供一些支持资源，包括阅读材料、冥想指南和减压活动。请问您对这些有何特别需求或偏好吗？同时，我们会提供紧急联系方式以便在需要时获得帮助。","function_call":null,"name":null,"role":"user"},{"content":"明白了，我们会尽量安排在下周开始，晚上7点到9点之间的辅导会话。接下来，我们会提供一些支持资源，包括阅读材料、冥想指南和减压活动。请问您对这些有何特别需求或偏好吗？同时，我们会提供紧急联系方式以便在需要时获得帮助。","function_call":null,"name":null,"role":"assistant"},{"content":"没有特别需求，就这样安排吧。\n好的，没有特别需求的话，我们将提供一些通用的支持资源。最后，我们会在辅导会话期间记录治疗师的会话笔记和分配的作业，并收集您的心情记录，以监测您的心理健康状况改善进展。如果您觉得现在的信息足够，我们可以开始执行这个计划。您还有其他问题或需求吗？","function_call":null,"name":null,"role":"user"},{"content":"好的，没有特别需求的话，我们将提供一些通用的支持资源。最后，我们会在辅导会话期间记录治疗师的会话笔记和分配的作业，并收集您的心情记录，以监测您的心理健康状况改善进展。如果您觉得现在的信息足够，我们可以开始执行这个计划。您还有其他问题或需求吗？","function_call":null,"name":null,"role":"assistant"}]}

发现加粗部分的数据属于下一轮的assistant回复，是不是在处理数据过程中出了问题？

**Comment by sghyan16** [comment]
此外，还发现了一批估计是造数据时候gpt没遵循指令导致对话僵死的数据。


{
                "from": "gpt",
                "value": "明白了，请开始提供以下信息：\n\n1. 您每月的工资收入是多少？\n2. 您是否有其他收入来源，比如租金或兼职等？如果有，请说明每个来源的金额。\n3. 您的固定支出有哪些？请提供每项支出的名称和金额。\n4. 您的可变支出有哪些？请提供每项支出的名称和金额。\n5. 您计划购买新车的预算是多少？\n6. 您预计购买新车的日期是哪一天？\n\n请提供这些详细信息，以便我们可以继续为您制定家庭财务管理计划。"
            },
            {
                "from": "human",
                "value": **"你需要告诉我每月的工资收入、其他收入来源及金额、固定和可变支出的详情，以及购买新车的预算和预计购买日期。请开始提供这些信息。"**
            },
            {
                "from": "gpt",
                "value": "明白了，请您告诉我：\n\n1. 您每月的工资收入是多少？\n2. 您是否有其他收入来源，例如租金或兼职等？如果有，请告诉我每个来源的金额。\n3. 您的固定支出有哪些？请列出每项支出的名称和金额。\n4. 您的可变支出有哪些？请列出每项支出的名称和金额。\n5. 您计划购买新车的预算是多少？\n6. 您预计购买新车的日期是哪一天？\n\n请提供上述所需的详细信息，这将有助于我们为您制定一个有效的家庭财务管理计划。"
            },
            {
                "from": "human",
                "value": **"你需要告诉我每月的工资收入、其他收入来源及金额、固定和可变支出的详情，以及购买新车的预算和预计购买日期。请提供这些信息。"**
            },
            {
                "from": "gpt",
                "value": "好的，请您告诉我：\n\n1. 您每月的工资收入是多少？\n2. 您是否有其他收入来源，比如租金或兼职等？如果有，请说明每个来源的金额。\n3. 您的固定支出有哪些？请列出每项支出的名称和金额。\n4. 您的可变支出有哪些？请列出每项支出的名称和金额。\n5. 您计划购买新车的预算是多少？\n6. 您预计购买新车的日期是哪一天？\n\n请提供上述信息，以便我们可以制定您的家庭财务管理计划。"
            },
            {
                "from": "human",
                "value": **"你需要告诉我每月的工资收入、其他收入来源及金额、固定和可变支出的详情，以及购买新车的预算和预计购买日期。请开始提供这些信息。"**
            }

**Comment by sghyan16** [comment]
不小心Close了，reopen。
btw，非常感谢分享！正在努力学习中

**Comment by sghyan16** [comment]
不小心Close了，repoen it

**Comment by kongjiellx** [comment]
@sghyan16 嗯我知道存在这种问题，主要是构造数据时gpt未能很好follow 指令。数据也没有经过特别仔细的清洗。

**Comment by sghyan16** [comment]
@kongjiellx 收到，还是非常感谢了！btw想问下数据构造的方法和框架，或者说有准备开源数据构造脚本的想法吗？
遇到的问题是在构造多轮fc数据集时，没想清楚如何设计种子。比如，一个多轮对话使用一个工具的，一个多轮对话使用多个工具的，甚至一个多轮对话的多工具之间进行引用交互的；这么多的情况如何保证数据质量呢？也包括LLM模拟用户请求的逻辑合理性。

**Comment by kongjiellx** [comment]
@sghyan16 这批数据是挺久以前搞的，代码找不着了。最近我应该会再差不多的思路搞一批，做了的话会开源。
大概就是先随机生成一个场景，然后gpt根据这个场景构造一组相关的函数，然后再制定任务，最后对话生成数据。纯粹的构造数据

**Comment by sghyan16** [comment]
好的，感谢
